[package]
name = "libmcp"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "../../README.md"
categories.workspace = true
keywords.workspace = true

[dependencies]
libmcp-derive = { version = "2.0.0", path = "../libmcp-derive" }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
url.workspace = true

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[lints]
workspace = true
